### ISSUE TITLE
[Probably user error] Trying to bundle neovim with configs

### ISSUE THREAD

**Issue by sivertism** [ralismark/nix-appimage#16]
Hi,
I'm trying to bundle neovim with configs so that I can use it outside of Nix/NixOS. Thought this AppImage bundler could be a good way of doing that. Being able to pass along an AppImage to whatever server I'm working in would be great.

So I tried
```
> nix bundle --bundler github:ralismark/nix-appimage github:sivertism/kickstart-nix.nvim
```

However, I'm getting an error:

```
error: path '/nix/store/<hash>-neovim-0.10.0/bin/nvim' is not in the Nix store
```

Any idea what causes this and how I might fix it?

**Comment by sivertism** [comment]
Update: I tried the example in the README and I get a similar error, but this time about `hello` missing
```
> nix bundle --bundler github:ralismark/nix-appimage nixpkgs#hello
```

->

```
error: path '/nix/store/<hash>-hello-2.12.1/bin/hello' is not in the Nix store
```

**Comment by matthiasdotsh** [comment]
Same here:

```bash
# Older verison works fine:
$ nix bundle --bundler 'github:ralismark/nix-appimage?rev=46aef0153eb833e0b896b60ca2bdb6354b410e45' nixpkgs#hello

# Latest version fails:
$ nix bundle --bundler 'github:ralismark/nix-appimage?rev=91971c6b37fe939b159fb54c130c187c947a8269' nixpkgs#hello
error: path '/nix/store/hs3yxdq9knimwdm51gvbs4dvncz46f9d-hello-2.12.1/bin/hello' is not in the Nix store
```

**Comment by sivertism** [comment]
Can confirm that the older version works for me as well, thanks @matthiasdotsh!

**Comment by ralismark** [comment]
Ah yikes, seems to be a problem with nix itself:

- https://github.com/NixOS/nixpkgs/issues/316652
- https://github.com/NixOS/nix/pull/10549

Supposedly fixed with newer versions of Nix, but to avoid forcing everyone to update I'll add a workaround.
