### ISSUE TITLE
Create a script that allows specifying the binary to package

### ISSUE THREAD

**Issue by ralismark** [ralismark/nix-appimage#3]
See #2. Ideally something like `./nix-bundle.sh` from https://github.com/matthewbauer/nix-bundle/

**Comment by ralismark** [comment]
I added the `./bundle` script, which should do exactly this.

**Comment by baduhai** [comment]
Thanks for the script. This is a pretty good workaround. I wish this was supported in the nix bundle spec, though.

**Comment by Cloudef** [comment]
Could this script be exposed by the flake as a app so one could `nix run github:ralismark/nix-appimage#bundle` it or something :slightly_smiling_face:
